version: '3.7'

services:
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    network_mode: host

  cameraevent:
    container_name: cameraevent
    image: cameraevent
    depends_on:
      - redis
    build: .
    network_mode: host

volumes:
  pulsar_data:
  pulsar_conf:
  prometheus_data:
  grafana_data:
