apiVersion: apps/v1
kind: Deployment
metadata:
  name: cameraevent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cameraevent
  template:
    metadata:
      labels:
        app: cameraevent
      annotations:
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
        logging.eencloud.com/mode: json-v1
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: cameraevent
          image: harbor.eencloud.com/test/cameraevent
          ports:
            - containerPort: 8082
          env:
          - name: APP_ENV
            value: "prod"
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
