apiVersion: v1
kind: Service
metadata:
  name: cameraevent-svc
spec:
  selector:
    app: cameraevent
  type: NodePort
  ports:
    - name: cameraevent-port
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: redis-port
      protocol: TCP
      port: 6379
      targetPort: 6379
